version: '2.2'
services:
  flyway-local:
    image: boxfuse/flyway:latest
    command: -configFiles=conf/flyway.conf migrate
    volumes:
      - ./migrations/conf:/flyway/conf
      - ./migrations/sql:/flyway/sql
    depends_on:
      - postgres
    links:
      - postgres:orders
  postgres:
    image: postgres:11
    ports:
      - "55432:5432"
    environment:
      - POSTGRES_PASSWORD=admin1234
      - POSTGRES_USER=admin
      - POSTGRES_DB=orderdb
